# Generated by Django 2.2.9 on 2020-02-03 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=500)),
                ('qty', models.IntegerField(default=0)),
                ('measurement', models.CharField(max_length=100)),
                ('original_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('supplier_name', models.CharField(max_length=500)),
                ('supplier_phone', models.CharField(max_length=500)),
                ('in_house', models.CharField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category')),
            ],
        ),
    ]
