# Generated by Django 2.2.9 on 2020-01-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('order_submit', models.CharField(blank=True, max_length=200, null=True)),
                ('order_delivered', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice_total', models.IntegerField(blank=True, default=0, null=True)),
                ('payment_choices', models.CharField(blank=True, choices=[('Cash on Delivery', 'Cash on Delivery'), ('Bkash', 'Bkash'), ('Bank', 'Bank')], max_length=100, null=True)),
                ('deposit', models.IntegerField(blank=True, default=0, null=True)),
                ('due', models.IntegerField(blank=True, default=0, null=True)),
                ('remarks', models.CharField(blank=True, default='N/A', max_length=1000, null=True)),
            ],
        ),
    ]
