# Generated by Django 2.2.9 on 2020-01-27 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientsorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsorder',
            name='clients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Clients'),
        ),
    ]
