# Generated by Django 2.2.9 on 2020-01-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientsorder_clients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsorder',
            name='due',
        ),
    ]
