# Generated by Django 2.2.9 on 2020-02-02 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0004_remove_clientsorder_due'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=200)),
                ('payment_type', models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('Bkash', 'Bkash'), ('Bank', 'Bank')], max_length=200)),
                ('invoice_total', models.IntegerField()),
                ('deposit', models.IntegerField()),
                ('due_collection_date', models.CharField(max_length=200)),
                ('order_delivered', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=1000)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Clients')),
            ],
        ),
    ]
