# Generated by Django 2.2.9 on 2020-02-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryorder',
            name='remarks',
            field=models.CharField(default='N/A', max_length=1000),
        ),
    ]
