# Generated by Django 2.2.9 on 2020-02-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_entryorder_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryorder',
            name='ref_no',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
